#!/bin/bash

THIS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]:-${(%):-%x}}" )" && pwd )
source "$THIS_DIR/../tools/common.sh"

if [[ -z "$1" || "$1" =~ "-h|--help" ]]; then
    fmt_info "usage: dogo <container>"
else
    $SUDO docker exec -it $1 zsh
fi
