name: sync dependencies to gitee
on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch: ~
jobs:
  ohmyzsh:
    runs-on: ubuntu-20.04
    steps:
    - name: ohmyzsh repo
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/ohmyzsh
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: "https"  # https/ssh
        debug: true  # print all commands
        force_update: true
        static_list: "ohmyzsh"
        timeout: '600s'
  zsh-users:
    runs-on: ubuntu-20.04
    steps:
    - name: zsh-users repos
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/zsh-users
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "antigen,zsh-syntax-highlighting,zsh-autosuggestions,zsh-completions"
        timeout: '600s'
  zdharma-continuum:
    runs-on: ubuntu-20.04
    steps:
    - name: zdharma-continuum repos
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/zdharma-continuum
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "fast-syntax-highlighting"
        timeout: '600s'
  tmux-mem-cpu-load:
    runs-on: ubuntu-20.04
    steps:
    - name: thewtex/tmux-mem-cpu-load
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/thewtex
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: user
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "tmux-mem-cpu-load"
        timeout: '600s'
  tmux-plugins:
    runs-on: ubuntu-20.04
    steps:
    - name: tmux-plugins
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/tmux-plugins
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "tpm,tmux-resurrect,tmux-yank"
        timeout: '600s'
  vundle-vim:
    runs-on: ubuntu-20.04
    steps:
    - name: VundleVim/Vundle-vim
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/VundleVim
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: org
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "Vundle.vim"
        timeout: '600s'
  onedark-vim:
    runs-on: ubuntu-20.04
    steps:
    - name: joshdick/onedark-vim
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/joshdick
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: user
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "onedark.vim"
        timeout: '600s'
  fzf:
    runs-on: ubuntu-20.04
    steps:
    - name: junegunn/fzf
      uses: Yikun/hub-mirror-action@v1.3
      with:
        src: github/junegunn
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: user
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "fzf"
        timeout: '600s'
