name: sync repos to gitee
on:
  push: ~
  workflow_dispatch: ~
jobs:
  dotfiles:
    runs-on: ubuntu-20.04
    steps:
    - name: DictXiong/dotfiles
      uses: Yikun/hub-mirror-action@v1.4
      with:
        src: github/DictXiong
        dst: gitee/dictxiong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        src_account_type: user
        dst_account_type: user
        clone_style: "https"
        debug: true
        force_update: true
        static_list: "dotfiles"
        timeout: '600s'
