name: test
on: 
  push: ~
  workflow_dispatch: ~
jobs:
  test-ubuntu:
    name: test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip zsh curl inetutils-ping
          sudo pip3 install requests
      
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: install dfs
        run: |
          rev=`git rev-parse HEAD`
          pwd
          export DFS_NO_COMPILE=1 DFS_NO_UPDATE=1
          ./install.sh
          test `git rev-parse HEAD` = "$rev"

      - name: antigen build
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: |
          echo $SHELL
          antigen list
          antigen reset

      - name: antigen build with DFS_NO_WALL
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        env:
          DFS_NO_WALL: 1
        run: |
          echo $SHELL
          antigen list

      - name: run tests
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: source tools/test.zsh
  
  test-macos:
    name: test on macos
    runs-on: macos-12
    steps:
      - name: install dependencies
        run: |
          brew update
          brew install git python3 zsh curl
          sudo pip3 install requests

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dfs
        run: |
          rev=`git rev-parse HEAD`
          pwd
          export DFS_NO_COMPILE=1 DFS_NO_UPDATE=1
          ./install.sh
          test `git rev-parse HEAD` = "$rev"

      - name: antigen build
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: |
          echo $SHELL
          antigen list

      - name: run tests
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: source tools/test.zsh