name: test
on: 
  push: ~
  workflow_dispatch: ~
jobs:
  test-ubuntu:
    name: test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-pip zsh curl inetutils-ping
          sudo apt remove -y vim tmux
          sudo pip3 install requests
      
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: install dfs
        run: |
          rev=`git rev-parse HEAD`
          pwd
          ./install.sh
          git checkout $rev

      - name: antigen build
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: |
          echo $SHELL
          antigen list
      
      - name: run tests
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: source tools/test.zsh
  
  test-macos:
    name: test on macos
    runs-on: macos-latest
    steps:
      - name: install dependencies
        run: |
          brew update
          brew install git python3 zsh curl
          brew remove vim tmux
          sudo pip3 install requests
      
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: install dfs
        run: |
          rev=`git rev-parse HEAD`
          pwd
          ./install.sh
          git checkout $rev

      - name: antigen build
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: |
          echo $SHELL
          antigen list
      
      - name: run tests
        shell: /bin/zsh -ileo PIPE_FAIL {0}
        run: source tools/test.zsh